method: "roundrobin" # "twochoice", "random", etc.
port: 2839
# network: "tcp" # or "udp"
# tls:  true

nodes:
  - address: "127.0.0.1"
    port: "8001"
    health: "/"
  - address: "127.0.0.1"
    port: "8002"
    health: "/"
  - address: "127.0.0.1"
    port: "8003"
    health: "/"