version: "3"
services:
  pblb:
    build: .
    ports:
      - 2839:2839
      - 2840:2840
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  nginx_a:
    image: nginx:latest
    container_name: nginx_a
    ports:
      - 80
  nginx_b:
    image: nginx:latest
    container_name: nginx_b
    ports:
      - 80
  nginx_c:
    image: nginx:latest
    container_name: nginx_c
    ports:
      - 80
