version: "3"
services:
  pblb:
    build: .
    ports:
      - 2839:2839
  nginx_a:
    image: nginx:latest
    container_name: nginx_a
    ports:
      - 80
  nginx_b:
    image: nginx:latest
    container_name: nginx_b
    ports:
      - 80
  nginx_c:
    image: nginx:latest
    container_name: nginx_c
    ports:
      - 80
